import { Student } from "./interface.js";
const students  : Student [] =
[
     {
    id:1,
    firstName:"MAHEEN",
    lastname:"IMTIAZ",
    rollno:416781,
    email:"maheenimtiaz536@gmail.com",
    isonsiteallowed:true,
    entrytest: {
        ispassed:true,
        obtainedmarks:80,
        totalmarks:100
    }
}
,{
    id:2,
    firstName:"ANOOSHA",
    lastname:"BAIG",
    rollno:416782,
    email:"anooshabaig4336@gmail.com",
    isonsiteallowed:true,
    entrytest:{
        ispassed:true,
        obtainedmarks:80,
        totalmarks:100
    }
},
{
    id:3,
    firstName:"AFIA",
    lastname:"MONIS",
    rollno:416783,
    email:"afiabjh67@gmail.com",
    isonsiteallowed:false,
    entrytest:{
        ispassed:false,
        obtainedmarks:40,
        totalmarks:100
    }
},{
    id:4,
    firstName:"HAFSA",
    lastname:"KAMALI",
    rollno:416784,
    email:"hafsakamli@gmail.com",
    isonsiteallowed:true,
    entrytest:{
        ispassed:true,
        obtainedmarks:80,
        totalmarks:100
    }
},
{
    id:5,
    firstName:"sarkan",
    lastname:"bolat",
    rollno:416785,
    email:"chasemansmil@gmail.com",
    isonsiteallowed:false,
    entrytest:{
        ispassed:false,
        obtainedmarks:30,
        totalmarks:100
    }
},{
    id:6,
    firstName:"eda",
    lastname:"yeildise",
    rollno:416786,
    email:"edaye9087@gmail.com",
    isonsiteallowed:true,
    entrytest:{
        ispassed:true,
        obtainedmarks:80,
        totalmarks:100
    }
},{
    id:7,
    firstName:"laila",
    lastname:"kyias",
    rollno:416787,
    email:"kayiakilaila@gmail.com",
    isonsiteallowed:false,
    entrytest:{
        ispassed:false,
        obtainedmarks:30,
        totalmarks:100
    }
},{
    id:8,
    firstName:"sanem",
    lastname:"jan",
    rollno:416788,
    email:"jankisanem23@gmail.com",
    isonsiteallowed:true,
    entrytest:{
        ispassed:true,
        obtainedmarks:80,
        totalmarks:100
    }
},{
    id:9,
    firstName:"kushi",
    lastname:"arnav",
    rollno:416789,
    email:"arnavsinghraizada@gmail.com",
    isonsiteallowed:false,
    entrytest:{
        ispassed:false,
        obtainedmarks:35,
        totalmarks:100
    }
},{
    id:10,
    firstName:"PIA",
    lastname:"ABHAY",
    rollno:416790,
    email:"abhyrajbeer@gmail.com",
    isonsiteallowed:true,
    entrytest:{
        ispassed:true,
        obtainedmarks:90,
        totalmarks:100
    }
}
]
export default students;